name: coffee_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.8.0
  flutter_spinkit: ^5.2.1
  google_maps_flutter: ^2.10.1
  url_launcher: ^6.3.1
  shared_preferences: ^2.5.2
  share_plus: ^10.1.4
  geocoding: ^3.0.0
  pocketbase: ^0.22.0
  flutter_dotenv: ^5.2.1
  http: ^1.3.0
  image_picker: ^1.1.2
  dio: ^5.8.0+1
  multi_select_flutter: ^4.1.3
  path_provider: ^2.1.5
  pdf: ^3.11.3

flutter_icons:
  android: true
  ios: true
  image_path: assets/images/logoapp.png
  adaptive_icon_background: "#FFFFFF"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/images/
